# Generated by Django 5.0.6 on 2024-05-31 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0002_deporte_remove_producto_imagen_mensaje_fondo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='subtitulo',
            field=models.CharField(default='¡Encuentra todo lo que necesita para mentenerte', max_length=200),
        ),
    ]
