# Generated by Django 5.0.6 on 2024-06-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0003_alter_mensaje_subtitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
