# Generated by Django 5.0.6 on 2024-06-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0005_estadio'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='imagen1',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio1.jpeg', null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen2',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio2.jpeg', null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen3',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio3.jpeg', null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen4',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio4.jpeg', null=True, upload_to='imagenes'),
        ),
    ]
