# Generated by Django 5.0.6 on 2024-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0006_estadio_imagen1_estadio_imagen2_estadio_imagen3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='pais',
            field=models.CharField(default='pais', max_length=200),
        ),
    ]
