# Generated by Django 5.0.6 on 2024-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0007_estadio_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadio',
            name='descripcion',
            field=models.CharField(default='descripcion ', max_length=200),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nombre',
            field=models.CharField(default='deporte ', max_length=200),
        ),
    ]
