# Generated by Django 5.0.6 on 2024-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0008_alter_estadio_descripcion_alter_estadio_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadio',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='estadio',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='estadio',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='estadio',
            name='imagen4',
        ),
        migrations.AddField(
            model_name='estadio',
            name='galeria_fotos',
            field=models.ManyToManyField(to='Deportes.producto'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='descripcion',
            field=models.CharField(default='Descripción', max_length=200),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nombre',
            field=models.CharField(default='Estadio', max_length=200),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='pais',
            field=models.CharField(default='País', max_length=200),
        ),
    ]
