# Generated by Django 5.0.6 on 2024-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0009_remove_estadio_imagen1_remove_estadio_imagen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadio',
            name='galeria_fotos',
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen1',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio1.jpeg', null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen2',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio2.jpeg', null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen3',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio3.jpeg', null=True, upload_to='imagenes'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='imagen4',
            field=models.ImageField(blank=True, default='/Deportes/media/estadio4.jpeg', null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='descripcion',
            field=models.CharField(default='descripcion', max_length=200),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nombre',
            field=models.CharField(default='deporte ', max_length=200),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='pais',
            field=models.CharField(default='pais', max_length=200),
        ),
    ]
